replicatCount: 1

image:
  repository: jakeprem/scos-sauron
  tag: latest
  pullPolicy: Always

monitoring:
  targetPort: 80

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  securityGroups: ""
  certificateARN: ""
  dnsZone: "localhost"

resources:
  limits:
    memory: 256Mi
    cpu: 150m
  requests:
    memory: 256Mi
    cpu: 50m

redis:
  host: redis.external-services

kafka:
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092