apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: waterwheel
  namespace: {{ .Release.Namespace }}
  labels:
    app: waterwheel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterwheel
  template:
    metadata:
      labels:
        app: waterwheel
    spec:
      containers:
      - name: waterwheel
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host }}
          - name: KAFKA_BROKERS
            value: {{ .Values.kafka.brokers }}
