apiVersion: v1
kind: Service
metadata:
  name: waterwheel
  namespace: {{ .Release.Namespace }}
  labels:
    app: waterwheel
spec:
  selector:
    app: waterwheel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
